# Generated by: ../proton-ge-custom/configure.sh --enable-ccache --build-name=GE-Proton9-1 --container-engine=podman

SRCDIR     := ../proton-ge-custom
BUILD_NAME := GE-Proton9-1
ROOTLESS_CONTAINER := 1
CONTAINER_ENGINE := podman
ENABLE_CCACHE := 1

include $(SRCDIR)/Makefile.in
